# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: GDG DevFest Netherlands
email: info@devfest.nl
description: "GDG DevFest Netherlands is part of a series of GDG DevFest events all around the world"
baseurl: ""
url: "http://www.devfest.nl"
permalink: /blog/:title
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "dutchaug.github.io"

# Organizer Info
organizerName: "GDG Dutch Android User Group"
organizerAlternateName: "The Dutch Android User Group"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "info@devfest.nl"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://www.dutchaug.org"

# Head
metaKeywords: "event, gdg, devfestnl, devfest, google, programming, android, chrome, angularjs, polymer, go, developer, developers"
twitterAccount: "@devfestnl"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/sponsors/", text: "Partners"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {link: "https://developers.google.com", text: "Developers"}
bottomNavigationLinks:
 - {link: "http://j.mp/1odkbc8", text: "Become a speaker"}
 - {link: "http://devfestnl14.eventbrite.com/", text: "Reserve your seat"}
rightNavigationButtons:
 - {link: "http://j.mp/1odkbc8", text: "Become a speaker"}
 - {link: "http://devfestnl14.eventbrite.com/", text: "Reserve your seat"}

# Hero Block
heroTitle: "GDG DevFest <typeout> 2014"
eventDate: "November 8th, 2014"
typeoutTextValues: '"", "Season", "Amsterdam", "The Netherlands"'
heroButtons:
 - {url: "http://j.mp/1odkbc8", text: "Become a speaker"}
 - {url: "http://devfestnl14.eventbrite.com/", text: "Reserve your seat"}

# About Block
aboutTitle: "About GDG DevFestNL"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lot's of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 #- {title: "Hackathon", image: "hackathon.jpg", text: "Full-day free-style hackaton! Want some real teambuilding on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlock:
 - {count: "0", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "8", specialCharacter: "+", info: "hours", detail: "of pure Google technologies and fun!"}
 - {count: "0", specialCharacter: "+", info: "speakers", detail: "national and international"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus many workshops"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersCount: 0
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "The Faculty of Science"
eventLocationLink: "http://www.amsterdamsciencepark.nl/"
eventStreetAddress: "Science Park 904"
eventAddressLocality: "Amsterdam"
eventAddressLocalityRegion: "Amsterdam"
eventPostalCode: "1098 XH"
eventAddressCountry: "The Netherlands"
eventStartTime: "2014-11-08T10:00"
eventDoorTime: "09:30"
eventEndTime: "2014-11-08T18:00"
eventPlaceCoordinates: "52.3544534,4.9553595"
mapCenterCoordinates: "52.3544534,4.9553595"
mapMobileCenterCoordinates: "52.3544534,4.9553595"

# Venue Block
venueBlockTitle: "Venue"
venueTitle: "Science Park 904"
venueFeatures: ["The Faculty of Science", "A leading centre of academic research and education!", "Located in the heart of science in Amsterdam"]

## Logistics Location Block
#logisticsMapCenterCoordinates: "52.3544534,4.9553595"
#logisticsMapMobileCenterCoordinates: "52.3544534,4.9553595"

# Tweets Feed Block
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfestnl"
##twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Organizers Block
organizersTitle: "Organizers"
# Documents
c4pUrl: "http://j.mp/1odkbc8"
c4sponsorsUrl: "mailto:info@devfest.nl"

# Subscribe Block
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://dutchaug.us6.list-manage.com/subscribe?u=00dd8d0a15bf77f68bd75d643&id=3ce443d9a5"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Head
#metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
#twitterAccount: "@DevFestNL"
#socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
#socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
#socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Buy Tickets Block
ticketsTitle: "Free entrance!"
ticketsOffers:
 -
  name: "Reserve one of 250 seats"
  price: "&euro;0,-"
  buyButtonLink: "http://devfestnl14.eventbrite.com/"
  buyButtonText: "Reserve your seat now!"
  ticketContentList: ["The GDG Dutch Android User Group and GDG Netherlands join forces in bringing you a single day event in the style of a true Google DevFest. This means interesting talks and hands-on labs, brought to you by national and international leaders using Google technology, in an informal setting, an inspirational environment with lots of room for open discussion and time to meet!"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-11-07T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/113182948271879290904", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=DevFestNL", icon: "twitter"}
 - {link: "https://www.facebook.com/groups/dutchaug/?fref=ts", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.dutchaug.org/", text: "The Dutch Android User Group"}
   - {link: "http://www.gdgnl.org/", text: "Google Developer Groups Netherlands"}
   - {link: "https://developers.google.com/", text: "Google Developers"}
 -
  title: "Contact"
  links:
   - {link: "mailto:info@devfest.nl", text: "info@devfest.nl"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

## About Event Block
#eventName: "GDG DevFest NL"

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestnl"

# Speakers List Block
showSessions: false
thumbnailsFolder: /img/speakers/

# Team Block
teamBlockTitle: "About us"
aboutUs: "The GDG Dutch Android User Group and GDG Netherlands join forces in bringing you a single day event in the style of a true Google DevFest. This means interesting talks and hands-on labs, brought to you by national and international leaders using Google technology, in an informal setting, an inspirational environment with lots of room for open discussion and time to meet!"

# Logistics Find Way Block
findWayTitle: "Find your way here"
logisticsMapCenterCoordinates: "52.3544534,4.9553595"
logisticsMapMobileCenterCoordinates: "52.3544534,4.9553595"

# Logistics Direction Details Block
directionDetailsTitle: "The Faculty of Science"
directionDetailsCards:
 - {title: "By car", information: 'The Faculty of Science (Science Park 904) is easily reachable by car. <a href="http://www.amsterdamsciencepark.nl/location-facilities/directions/directions-by-car/">More info</a>'}
 - {title: "Public Transit", information: 'There is a train station, metro station and a bus stop nearby. <a href="http://www.amsterdamsciencepark.nl/location-facilities/directions/directions-by-public-transport/">More info</a>'}
 - {title: "Parking", information: 'Lots of parking spaces nearby. Aim for parking P3 and walk from there. <a href="http://www.amsterdamsciencepark.nl/location-facilities/directions/parking/">More info</a>'}